### ISSUE TITLE
Mark all user-visible strings as translatable in C++

### ISSUE THREAD

**Issue by lassoan** [Slicer/SlicerLanguagePacks#12]
## Summary

Many strings that are specified in C++ source files have not been marked as translatable (e.g., by using the `QObject::tr` method). Slicer core, CTK library, and Slicer extensions source code needs to be improved so that all translatable strings are marked as such.

## Evolution of modules marking tasks

- [x]  [Mark translatable strings in EventBroker module](https://github.com/Slicer/Slicer/pull/6644)
- [x]  [Mark translatable strings in Data module](https://github.com/Slicer/Slicer/pull/6644)
- [x]  [Mark translatable strings in DataProbe module](https://github.com/Slicer/Slicer/pull/6960)
- [x] [Mark translatable strings in BaseQTGUI](https://github.com/Slicer/Slicer/pull/6704)
- [x] [Mark translatable strings in BaseQTCore](https://github.com/Slicer/Slicer/pull/6768)
- [x] [Mark translatable strings in BaseQTApp](https://github.com/Slicer/Slicer/pull/6784)
- [x] [Mark translatable strings in BaseQTCli](https://github.com/Slicer/Slicer/pull/6821)
- [x] Mark translatable strings in Cameras module
  - remaining issues are now tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/65 and https://github.com/Slicer/SlicerLanguagePacks/issues/64
- [x] Mark translatable strings in Colors module
  - https://github.com/Slicer/SlicerLanguagePacks/issues/59
  - https://github.com/Slicer/SlicerLanguagePacks/issues/69
- [x] Mark translatable strings in CropVolume module
  - remaining issues are now tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/65 and https://github.com/Slicer/SlicerLanguagePacks/issues/64
- [x] Mark translatable strings in Markups module - now tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/37
- [x] Mark translatable strings in Models module - remaining issue is tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/69
- [x] Mark translatable strings in Plots module - remaining issue is tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/69
- [x] Mark translatable strings in Reformat module - remaining issues
  - https://github.com/Slicer/SlicerLanguagePacks/issues/66
  - https://github.com/Slicer/SlicerLanguagePacks/issues/69
- [x] Mark translatable strings in SceneViews module => now tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/70
- [x] [Mark translatable strings in Segmentations module](https://github.com/Slicer/Slicer/pull/6948)
- [x] Mark translatable strings in SlicerWelcome module
- [x] Mark translatable strings in SubjectHierarchy module - now tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/71
- [x] Mark translatable strings in Terminologies module
  - https://github.com/Slicer/SlicerLanguagePacks/issues/69
  - https://github.com/Slicer/SlicerLanguagePacks/issues/67
- [x] Mark translatable strings in Texts module - remaining issue is tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/69
- [x] Mark translatable strings in Transforms module
  - https://github.com/Slicer/SlicerLanguagePacks/issues/69
  - https://github.com/Slicer/SlicerLanguagePacks/issues/65
- [x] Mark translatable strings in Units module - remaining issue is tracked in https://github.com/Slicer/SlicerLanguagePacks/issues/68
- [x] Mark translatable strings in ViewControllers module
  - https://github.com/Slicer/SlicerLanguagePacks/issues/69
  - https://github.com/Slicer/SlicerLanguagePacks/issues/66
- [x] Mark translatable strings in VolumeRendering module
  - remaining issue: https://github.com/Slicer/SlicerLanguagePacks/issues/65
- [x] [Mark translatable strings in Volumes module](https://github.com/Slicer/Slicer/pull/6655)

**Comment by lassoan** [comment]
Qt seems to recommend two approaches for making `tr()` function available in non-QObject-based classes:
- Option A: Use `Q_DECLARE_TR_FUNCTIONS(MyClass)` macro (see https://doc-snapshots.qt.io/qt6-6.2/i18n-source-translation.html#translating-non-qt-classes)
- Option B: Use `QSomeWidget::tr()` (see https://doc-snapshots.qt.io/qt6-6.2/i18n-source-translation.html#using-tr-for-all-literal-text)

Probably option A is more clear and consistent - we can use `tr()` everywhere and only need to add a single line to the non-QObject-based class declaration. Of course, it would need to be tested if it indeed works as we expect.

**Comment by mhdiop** [comment]
I was wondering which approach we should use when it's about dealing with numbered arguments present on translatable strings. For example, when we have the following string :
```c++
QString("An update is available. Installed: %1. Available : %2.")
        .arg(installedVersion)
        .arg(onServerVersion);
```
Which translation approach should we consider ?

**Option A**

```c++
tr("An update is available. Installed: %1. Available: %2.")
        .arg(installedVersion)
        .arg(onServerVersion);
```

**Option B**

```c++
tr("%1 %2 %3. %4 %5.")
        .arg(tr("An update is available."))
        .arg(tr("Installed:"))
        .arg(installedVersion)
        .arg(tr("Available:"))
        .arg(onServerVersion);
```

**Option C**

```c++
tr("%1 %2. %3 %4.")
        .arg(tr("An update is available. Installed:"))
        .arg(installedVersion)
        .arg(tr("Available:"))
        .arg(onServerVersion);
```

The first option may be simpler and may offer more flexibility at translation time. It also offers a better context to the translation since the whole sentence is visible. However, the presence of arguments in translatable strings may not be understood by "non-tech" translators and may be mishandled.

For this, I think that, as with the `& character`, we can specify in the ongoing translation guide what they represent and how to handle them.

Here is another example of such strings where the text in the HTML code has numbered arguments and needs to be translated.

![unnamed](https://user-images.githubusercontent.com/103750673/203148714-d8a68f28-7ddc-4aa1-b1fc-a0e2a9d05fa5.png)

**Comment by lassoan** [comment]
All problems are fixed or tracked in specific issues.
