### ISSUE TITLE
Untranslated parts of the Slicer Phenotyping tutorial Slicer version 5.3.0 2023-04-05

### ISSUE THREAD

**Issue by Papa96108** [Slicer/SlicerLanguagePacks#24]
- [x] Description and alternative text of these button

![1](https://user-images.githubusercontent.com/78362404/230629984-f3df52fc-5ad6-4c9f-847f-33040f0dcc6c.png)

![2](https://user-images.githubusercontent.com/78362404/230630114-2fb33a50-c57f-4a7c-934c-0869c068a5e6.png)

- [x] Segment Statistics section

![3](https://user-images.githubusercontent.com/78362404/230630232-cf1d3e16-b472-4c52-b2a5-0e44170ee4eb.png)

- [x] Segment statistics table result 

![4](https://user-images.githubusercontent.com/78362404/230630552-bae230ea-f951-4887-9760-98eb8f4ef1dc.png)

- [x] Radiomics section -> tracked now in https://github.com/Slicer/SlicerLanguagePacks/issues/62
- [x] table of radiomics result -> tracked now in https://github.com/Slicer/SlicerLanguagePacks/issues/62

![5](https://user-images.githubusercontent.com/78362404/230630784-0319a878-c233-4cdd-ba09-325925585ef6.png)

- [x] This boxed part is translated into French and must be updated in the [Image Phenotyping tutorial](https://docs.google.com/presentation/d/1NCnVAaO-8_OoUJ0Xy9-oBnwO26TnPkR3/edit#slide=id.p30) -> it is tracked now in https://github.com/Slicer/SlicerLanguagePacks/issues/61

![image](https://github.com/Slicer/SlicerLanguagePacks/assets/105887351/27b6412d-e2b5-44e6-8096-2079c7114267)

**Comment by Papa96108** [comment]
- [ ] Description and alternative text of these button

![1](https://user-images.githubusercontent.com/78362404/230629984-f3df52fc-5ad6-4c9f-847f-33040f0dcc6c.png)

![2](https://user-images.githubusercontent.com/78362404/230630114-2fb33a50-c57f-4a7c-934c-0869c068a5e6.png)

- [ ] Segment Statistics section

![3](https://user-images.githubusercontent.com/78362404/230630232-cf1d3e16-b472-4c52-b2a5-0e44170ee4eb.png)

- [ ] Segment statistics table result 

![4](https://user-images.githubusercontent.com/78362404/230630552-bae230ea-f951-4887-9760-98eb8f4ef1dc.png)

- [ ] Radiomics section 
- [ ] table of radiomics result 

![5](https://user-images.githubusercontent.com/78362404/230630784-0319a878-c233-4cdd-ba09-325925585ef6.png)

**Comment by jamesobutler** [comment]
@Papa96108 There are still many parts of Slicer that are not marked for translating yet.

You can review the progress in the following list at https://github.com/Slicer/SlicerLanguagePacks/issues/12 and that not all Slicer scripted modules are marked for translation yet at https://github.com/Slicer/SlicerLanguagePacks/issues/21.

**Comment by lassoan** [comment]
@jamesobutler thanks for jumping in here. We actually asked @Papa96108 to report non-translatable parts of Slicer that are used in specific tutorials that we plan to translate to French. These issues help us to keep track of what still needs to be done.

**Comment by lassoan** [comment]
All the text in the screenshots above is from Python scripted modules. We are still working on the infrastructure that enables Pythong module translation.

**Comment by MohamedAllali** [comment]
@lassoan That's great.

**Comment by lassoan** [comment]
@FatouBintou22 please check if this is completed and if yes then close the issue. Thank you.

**Comment by FatouBintou22** [comment]
- [ ] This boxed part is translated into French and must be updated in the [Image Phenotyping tutorial](https://docs.google.com/presentation/d/1NCnVAaO-8_OoUJ0Xy9-oBnwO26TnPkR3/edit#slide=id.p30)

![image](https://github.com/Slicer/SlicerLanguagePacks/assets/105887351/27b6412d-e2b5-44e6-8096-2079c7114267)

- [ ] The untranslated parts mentioned above by @Papa96108  are translated except Radiomics
